production:
  daily_maintenance:
    class: DailyMaintenanceJob
    queue: background
    schedule: every day at 4:00am

development:
  daily_maintenance:
    class: DailyMaintenanceJob
    queue: background
    schedule: every day at 4:00am

