production:
  clear_finished_jobs:
    command: SolidQueue::Job.clear_finished_in_batches
    schedule: every day at 3:00am
  expire_old_ribbons:
    command: ReadRibbon.expire_old_ribbons!
    schedule: every day at 4:00am
  fill_flagged_cache:
    command: FlaggedCommenters.new("1m").commenters
    schedule: every 8 hours
  populate_comment_stats:
    command: CommentStat.daily_fill!
    schedule: every day at 4:00am
  restic:
    command: ResticJob
    schedule: every day at 1 am
  sitemap:
    command: SitemapGenerator::Interpreter.run(config_file: ENV["CONFIG_FILE"], verbose: false)
    schedule: every day at 2 am
  stats_graphs:
    class: StatsGraphsJob
    schedule: every day at 12:00am

development:
  clear_finished_jobs:
    command: SolidQueue::Job.clear_finished_in_batches
    schedule: every day at 3:00am
  expire_old_ribbons:
    command: ReadRibbon.expire_old_ribbons!
    schedule: every day at 4:00am
  populate_comment_stats:
    command: CommentStat.daily_fill!
    schedule: every day at 4:00am
  stats_graphs:
    class: StatsGraphsJob
    schedule: every day at 12:00am
