production:
  expire_old_ribbons:
    class: ExpireOldRibbonsJob
    queue: background
    schedule: every day at 4:00am
  populate_comment_stats:
    class: PopulateCommentStatsJob
    queue: background
    schedule: every day at 4:00am
  stats_graphs:
    class: StatsGraphsJob
    queue: background
    schedule: every day at 4:15am
  clear_finished_jobs:
    class: ClearFinishedJobsJob
    queue: background
    schedule: every day at 3:00am

development:
  expire_old_ribbons:
    class: ExpireOldRibbonsJob
    queue: background
    schedule: every day at 4:00am
  populate_comment_stats:
    class: PopulateCommentStatsJob
    queue: background
    schedule: every day at 4:00am
  stats_graphs:
    class: StatsGraphsJob
    queue: background
    schedule: every day at 4:15am
  clear_finished_jobs:
    class: ClearFinishedJobs
    queue: background
    schedule: every day at 3:00am
